### ISSUE TITLE
Is there documentation for optional vs mandatory in codex?

### ISSUE THREAD

**Issue by memiah-nick** [passivsystems/protean#184]
I note the use of :optional - is mandatory assumed when this isn't present, or is there a :mandatory equivalent?

**Comment by rossm-memiah** [comment]
I actually can't remember.  I could not find any specific use of mandatory in the petstore example codex.  Nor did I either document this on proteanic.org or do a very good job of documenting it.

Sorry, over to the guys with this one.

**Comment by colin-passiv** [comment]
we had defined `:required` as the opposite to `:optional`, but in practice protean considers anything without :optional as mandatory.

In generated docs, we just display any tags associated with the query param, so it's good practice to use :required since it makes the docs clearer - though we could potentially improve the docs to include :required automatically whenever :optional is not present.

**Comment by rossm-memiah** [comment]
Thanks Colin.  Got it.

**Comment by memiah-nick** [comment]
Great, thanks
